import { Component, OnInit } from '@angular/core';
import { Article, ArticleApi } from './sdk';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  public articles: Article[];

  constructor(
    /**
     * The articleApi is an API that contains functions to work with the
     * article model on the back-end. It is basically an elaborate wrapper
     * to perform API requests to the back-end server.
     *
     * It is automatically generated by the loopback-sdk-builder, the documentation
     * is here https://github.com/mean-expert-official/loopback-sdk-builder/wiki
     */
    private articleApi: ArticleApi
  ) { }

  /**
   * OnInit is a function that Angular calls whenever the page is loaded. It is useful
   * for populating variables with data from a back-end for example.
   */
  public ngOnInit() {

    /**
     * The `find()` method retrieves all instances of the model. It returns an
     * observable, which is a particular kind of object that you will see a lot in
     * Typescript. You can 'subscribe' to it using its `subscribe()` method with a
     * callback.
     *
     * Go ahead and google what Observables are and how they work (roughly, just the
     * basic usage should be enough)
     */
    this.articleApi.find()
      .subscribe((articles: Article[]) => {
        this.articles = articles;
      });
  }

  /**
   * This function adds one like to the corresponding
   * article.
   * @param id Id of the article to like
   */
  public like(id: number|string): void {
    /**
     * This function needs to be implemented. Make sure your remote method (on the back-end)
     * works. Also, remember that `this.articleApi` has all kinds of wrapper functions to
     * work with the back-end model.
     */
  }
}
