import { Component, OnInit } from '@angular/core';
import { Article, ArticleApi } from './sdk';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  public articles: Article[];

  constructor(
    /**
     * The articleApi is an API that contains functions to work with the
     * article model on the back-end. It is basically an elaborate wrapper
     * to perform API requests to the back-end server.
     *
     * It is automatically generated by the loopback-sdk-builder, the documentation
     * is here https://github.com/mean-expert-official/loopback-sdk-builder/wiki
     */
    private articleApi: ArticleApi
  ) { }

  /**
   * OnInit is a function that Angular calls whenever the page is loaded. It is useful
   * for populating variables with data from a back-end for example.
   */
  public ngOnInit() {
    this.articleApi.find()
      .subscribe((articles: Article[]) => {
        this.articles = articles;
      });
  }
}
